chore(build): add explicit dependency for java 21 upgrade
Going forward we should use jdk21 for newer versions of intellij
this causes org/opentest4j/AssertionFailedError
java.lang.NoClassDefFoundError: org/opentest4j/AssertionFailedError
errors due to it not correctly being added to the classpath

Adding an explicit dependency will stop that happening when we eventually upgrade